### ISSUE TITLE
Wrong index in CoarseNFineDataset when using the TestFASTALoader

### ISSUE THREAD

**Issue by MoritzErtelt** [microsoft/seq2symm#2]
Hi there, really cool work!

I came across a little index bug that leads to every FASTA sequence being predicted as `C3`.

The `TestFASTALoader` Class creates a dict like this `(sequence_name, "", '###', "", "U", sequence)`:
https://github.com/microsoft/seq2symm/blob/7e87dc3afbf3bf47657ab07f20ef84ee33590f43/src/data_loader.py#L536-L540
but the `CoarseNFineDataset` accesses the `U` instead of the `sequence` column (index 4 vs 5) and therefore `C3` is always predicted for all sequences:
https://github.com/microsoft/seq2symm/blob/7e87dc3afbf3bf47657ab07f20ef84ee33590f43/src/data_loader.py#L776-L779

**Comment by meghana-kshirsagar** [comment]
Thanks for fixing this bug!
